# Generated by Django 4.1.7 on 2023-03-30 11:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('LittleLemonAPI', '0002_remove_cart_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='unit_price',
        ),
    ]
